token:
  expiration_time: 864000000
  secret: '{cipher}AQAjT/NUbYk3dC1yHQk3l1R9sn+8Vakv6b1ix0pqPbPnHf8xKBtLV4QvuyQB1PRNgnxNvN3fC5Tozr72TtF325zWQlrffXqe4qKBEAFPenRCQ6UqMWw/ZT0fdzsMb2u2c/1uc3SwEQCkT5PCx6DrNx6+vyX/1mPrykn6L+sMiILNFEQmge0tpAXtD4QMhtRMeEW9DchO1F629/c9Z5vT1NZVF5hj6BuQN8gXVD994ZMspTR9q8pxS0tYxEyfWUuKIs9lWbEz1CpRvc79PICXV8ambapjQ7Wpo75uT8R2jTPXo59We/hFpLRWfiJng+IJpY7MMfy8R/89zcVkz1NnIiEj17zT3oEWoovEhYfOxKqhyYb1n1lxw9/Ed+pg4c92Ab4VyrSys8Pai6IKcrAiR7My'

gateway:
  ip: 172.18.0.5
